n1 = int(input("Enter the number of fruits in set s1: "))
s1 = set()
print("Enter fruits for set s1:")
for i in range(n1):
    fruit = input()
    s1.add(fruit)
n2 = int(input("Enter the number of fruits in set s2: "))
s2 = set()
print("Enter fruits for set s2:")
for i in range(n2):
    fruit = input()
    s2.add(fruit)
common_fruits = s1.intersection(s2)
print("Fruits in both sets:", common_fruits)
unique_to_s1 = s1.difference(s2)
print("Fruits only in s1:", unique_to_s1)
total_fruits = s1.union(s2)
total_fruits_count = len(total_fruits)
print("Count of all fruits from s1 and s2:", total_fruits_count)